import {ResponseApi} from "./types";

const errors: { [x: string]: ResponseApi<undefined> } = {
    'Bad Request': {code: 400, error: true, message: 'Bad Request'},
    'Error generating the pdf': {code: 500, error: true, message: 'Error generating the pdf'},
    'Incorrect credentials': {code: 400, error: true, message: 'Incorrect credentials check your data'},
    'Missing id': {code: 400, error: true, message: 'Missing id'},
    'Missing fields': {code: 400, error: true, message: 'Missing fields'},
    'Missing periods': {code: 400, error: true, message: 'Missing periods'},
    'Invalid fields': {code: 400, error: true, message: 'Invalid fields'},
    'Invalid id': {code: 400, error: true, message: 'Invalid id'},
    'Invalid year': {code: 400, error: true, message: 'Invalid year'},
    'Invalid data type': {code: 400, error: true, message: 'Invalid data type'},
    'Invalid name': {code: 400, error: true, message: 'Invalid name'},
    'Invalid lastname': {code: 400, error: true, message: 'Invalid lastname'},
    'Invalid email': {code: 400, error: true, message: 'Invalid email'},
    'Invalid password': {code: 400, error: true, message: 'Invalid password'},
    'Invalid order': {code: 400, error: true, message: 'Invalid order, please select ASC o DESC'},
    'Invalid sort by field': {code: 400, error: true, message: 'Invalid sortBy field, select a different field'},
    'Invalid filter by value': {code: 400, error: true, message: 'Invalid filter by value'},
    'Invalid filter by field': {code: 400, error: true, message: 'Invalid filter by field'},
    'Invalid phone number': {code: 400, error: true, message: 'Invalid phone number'},
    'Invalid extension number': {code: 400, error: true, message: 'Invalid extension number'},
    'Invalid role': {code: 400, error: true, message: 'Invalid role'},
    'Invalid document': {code: 400, error: true, message: 'Invalid document'},
    'Invalid status': {code: 400, error: true, message: 'Invalid status'},
    'Invalid Date': {code: 400, error: true, message: 'Invalid Date'},
    'Invalid reason': {code: 400, error: true, message: 'Invalid reason'},
    'Invalid period': {code: 400, error: true, message: 'Invalid period'},
    'Invalid goal': {code: 400, error: true, message: 'Invalid goal'},
    'Invalid indicator': {code: 400, error: true, message: 'Invalid indicator'},
    'Invalid quarter': {code: 400, error: true, message: 'Invalid quarter'},
    'Invalid processes': { code: 400, error: true, message: 'Invalid processes' },
    'Invalid area': { code: 400, error: true, message: 'Invalid area' },
    'Invalid activity': { code: 400, error: true, message: 'Invalid activity' },
    'Invalid Token': {code: 401, error: true, message: 'Unauthorized'},
    'Completed POA': {code: 400, error: true, message: 'Completed POA'},
    'Progress not validated': {code: 400, error: true, message: 'Progress not validated'},
    'Duplicate': {code: 400, error: true, message: 'Already exists'},
    'Already exists': {code: 400, error: true, message: 'Already exists'},
    'Not available': {code: 400, error: true, message: 'Not available'},
    'User occupied': {code: 400, error: true, message: 'User occupied'},
    'User disabled': {code: 400, error: true, message: 'User disabled'},
    'POA already exists': {code: 400, error: true, message: 'POA already exists'},
    'Area disabled': {code: 400, error: true, message: 'Area disabled'},
    'The period is closed': { code: 400, error: true, message: 'The period is closed' },
    'The period is not started': { code: 400, error: true, message: 'The period is not started' },
    'Process disabled': { code: 400, error: true, message: 'Process disabled' },
    'Too Much Data': {code: 400, error: true, message: 'Too Much Data'},
    'Expired Token': {code: 401, error: true, message: 'Expired Token'},
    'Unauthorized': {code: 401, error: true, message: 'Unauthorized'},
    'Forbidden': {code: 403, error: true, message: 'Forbidden'},
    'User not active': {code: 403, error: true, message: 'User not active'},
    'Without area user': {code: 403, error: true, message: 'Without area user'},
    'Not found period': {code: 404, error: true, message: 'Not found period'},
    'Not found': {code: 404, error: true, message: 'Not found'},
    'Not found file': {code: 404, error: true, message: 'Not found file'},
    'Not found evidence': {code: 404, error: true, message: 'Not found evidence'},
    'Not activities': {code: 404, error: true, message: 'Not activities'},
    'Error deleting file': {code: 500, error: true, message: 'Error deleting file'},
    'Error saving': {code: 500, error: true, message: 'Error saving'},
    'Error updating': {code: 500, error: true, message: 'Error updating'},
    'Error deleting': {code: 500, error: true, message: 'Error deleting'},
    'Error sending email': {code: 500, error: true, message: 'Error sending email'},
    'Server Error': {code: 500, error: true, message: 'Internal Server Error'},
    'Default': {code: 500, error: true, message: 'Internal Server Error'}
};

export const validateError = (error: Error): ResponseApi<undefined> => {
    return errors[error.message] || errors['Default'];
}